name: Publish

on:
  create:
    branches:
      - release/**
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      PROJECT_PATH: Funogram.Telegram

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Build solution and generate NuGet package
      run: |
        cd $PROJECT_PATH
        dotnet pack -c Release -o out

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./$PROJECT_PATH/out/*.nupkg -k ${NUGET_AUTH_TOKEN} -s ${NUGET_SOURCE} --skip-duplicate --no-symbols true